# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chessmonger"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["AlphaHydrae"]
  s.date = "2012-09-17"
  s.description = "Extensible grid game engine in Ruby."
  s.email = "hydrae.alpha@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    ".screenrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "chessmonger.gemspec",
    "lib/chessmonger.rb",
    "lib/chessmonger/config.rb",
    "lib/chessmonger/config/armory.rb",
    "lib/chessmonger/config/behaviors.rb",
    "lib/chessmonger/config/config.rb",
    "lib/chessmonger/config/notation.rb",
    "lib/chessmonger/config/variant.rb",
    "lib/chessmonger/engine.rb",
    "lib/chessmonger/engine/action.rb",
    "lib/chessmonger/engine/board.rb",
    "lib/chessmonger/engine/direction.rb",
    "lib/chessmonger/engine/game.rb",
    "lib/chessmonger/engine/move.rb",
    "lib/chessmonger/engine/piece.rb",
    "lib/chessmonger/engine/player.rb",
    "lib/chessmonger/engine/position.rb",
    "lib/chessmonger/notations.rb",
    "lib/chessmonger/notations/cmgn.rb",
    "lib/chessmonger/notations/errors.rb",
    "lib/chessmonger/rulebook.rb",
    "lib/chessmonger/rulebook/book.rb",
    "lib/chessmonger/rulebook/letter_serializer.rb",
    "lib/chessmonger/rulebook/rules_serializer.rb",
    "lib/chessmonger/variants.rb",
    "lib/chessmonger/variants/basic.rb",
    "lib/chessmonger/variants/international/king.rb",
    "lib/chessmonger/variants/international/pawn.rb",
    "lib/chessmonger/variants/international/rules.rb",
    "spec/compound_spec.rb",
    "spec/config/armory_spec.rb",
    "spec/config/behaviors_spec.rb",
    "spec/config/config_spec.rb",
    "spec/config/notation_spec.rb",
    "spec/config/variant_spec.rb",
    "spec/engine/action_spec.rb",
    "spec/engine/board_spec.rb",
    "spec/engine/direction_spec.rb",
    "spec/engine/game_spec.rb",
    "spec/engine/move_spec.rb",
    "spec/engine/piece_spec.rb",
    "spec/engine/player_spec.rb",
    "spec/engine/position_spec.rb",
    "spec/helper.rb",
    "spec/notations/cmgn_spec.rb",
    "spec/rulebook/book_spec.rb",
    "spec/rulebook/letter_serializer_spec.rb",
    "spec/rulebook/rules_serializer_spec.rb",
    "spec/variants/abstract_spec.rb",
    "spec/variants/international/king_spec.rb",
    "spec/variants/international/pawn_spec.rb",
    "spec/variants/international/rules_spec.rb",
    "spec/version_spec.rb"
  ]
  s.homepage = "http://github.com/AlphaHydrae/chessmonger"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Chess, Shogi and other variants."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake-version>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake-version>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake-version>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

